# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='old', unique=True),
            preserve_default=False,
        ),
    ]
